"""50 curated Indian government schemes for startups and MSMEs."""

SCHEMES_SEED = [
    {
        "code": "SISFS",
        "name_en": "Startup India Seed Fund Scheme (SISFS)",
        "name_hi": "स्टार्टअप इंडिया सीड फंड योजना",
        "category": "Central - Startup",
        "authority": "DPIIT, Ministry of Commerce",
        "grant_amount_inr": 2000000,
        "grant_amount_label_en": "Up to ₹20 lakh grant + ₹50 lakh convertible debenture",
        "grant_amount_label_hi": "₹20 लाख तक अनुदान + ₹50 लाख डिबेंचर",
        "summary_en": "Financial assistance for proof of concept, prototype development, product trials, market entry, and commercialization.",
        "summary_hi": "प्रोटोटाइप, उत्पाद परीक्षण, बाजार में प्रवेश और व्यावसायीकरण के लिए वित्तीय सहायता।",
        "eligibility": {
            "stages": ["idea", "dpiit", "revenue"],
            "dpiit_required": True,
            "max_age_years": 2,
            "sectors": ["any"],
            "women_led_bonus": False,
            "tech_bonus": True,
            "max_revenue_inr": 100000000
        },
        "documents": ["DPIIT Certificate", "Pitch Deck", "PAN Card", "GST Certificate", "Bank Statement", "Founder KYC"],
        "timeline": "45-60 days",
        "official_link": "https://seedfund.startupindia.gov.in/"
    },
    {
        "code": "TIDE2",
        "name_en": "TIDE 2.0 (Technology Incubation & Development of Entrepreneurs)",
        "name_hi": "टाइड 2.0",
        "category": "Central - Tech Startup",
        "authority": "MeitY",
        "grant_amount_inr": 700000,
        "grant_amount_label_en": "₹4-7 lakh grant + incubation support",
        "grant_amount_label_hi": "₹4-7 लाख अनुदान + इनक्यूबेशन सहायता",
        "summary_en": "Supports tech startups in emerging areas like IoT, AI, blockchain, robotics, AR/VR.",
        "summary_hi": "IoT, AI, ब्लॉकचेन, रोबोटिक्स, AR/VR जैसे उभरते क्षेत्रों में तकनीकी स्टार्टअप का समर्थन।",
        "eligibility": {"stages": ["idea", "dpiit"], "dpiit_required": False, "sectors": ["tech", "ai", "iot", "saas"], "tech_bonus": True, "max_age_years": 3},
        "documents": ["Incorporation Certificate", "Founder Aadhaar/PAN", "Product Prototype", "Pitch Deck"],
        "timeline": "60-90 days",
        "official_link": "https://tide.meity.gov.in/"
    },
    {
        "code": "NIDHI_PRAYAS",
        "name_en": "NIDHI-PRAYAS (Promoting and Accelerating Young and ASpiring Innovators)",
        "name_hi": "निधि-प्रयास",
        "category": "Central - Prototype",
        "authority": "DST, Government of India",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh for prototype development",
        "grant_amount_label_hi": "प्रोटोटाइप विकास के लिए ₹10 लाख तक",
        "summary_en": "Grants for innovators to convert ideas into prototypes.",
        "summary_hi": "विचारों को प्रोटोटाइप में बदलने के लिए अनुदान।",
        "eligibility": {"stages": ["idea"], "sectors": ["tech", "hardware", "biotech"], "tech_bonus": True, "max_age_years": 2},
        "documents": ["Innovation Proposal", "Founder KYC", "College/Institute Affiliation (if student)"],
        "timeline": "90 days",
        "official_link": "https://www.nstedb.com/institutional/nidhi.htm"
    },
    {
        "code": "MEITY_SAMRIDH",
        "name_en": "MeitY SAMRIDH Accelerator Program",
        "name_hi": "मीटी समृद्धि",
        "category": "Central - Tech Growth",
        "authority": "MeitY",
        "grant_amount_inr": 4000000,
        "grant_amount_label_en": "Up to ₹40 lakh + matching investor funding",
        "grant_amount_label_hi": "₹40 लाख तक + निवेशक फंडिंग",
        "summary_en": "For product-based software startups ready to scale with customer traction.",
        "summary_hi": "उत्पाद-आधारित सॉफ्टवेयर स्टार्टअप के लिए जो स्केल के लिए तैयार हैं।",
        "eligibility": {"stages": ["revenue"], "dpiit_required": True, "sectors": ["saas", "tech", "ai"], "tech_bonus": True, "min_revenue_inr": 500000},
        "documents": ["DPIIT Certificate", "Revenue Statement", "Customer References", "Pitch Deck"],
        "timeline": "60 days",
        "official_link": "https://meitystartuphub.in/samridh/"
    },
    {
        "code": "MSME_CHAMPIONS",
        "name_en": "MSME Champions Scheme",
        "name_hi": "एमएसएमई चैंपियंस योजना",
        "category": "Central - MSME",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh for technology upgradation",
        "grant_amount_label_hi": "प्रौद्योगिकी उन्नयन के लिए ₹15 लाख तक",
        "summary_en": "Financial support for MSMEs to modernize and become globally competitive.",
        "summary_hi": "एमएसएमई को आधुनिक बनाने और वैश्विक स्तर पर प्रतिस्पर्धी बनाने के लिए सहायता।",
        "eligibility": {"stages": ["revenue"], "sectors": ["manufacturing", "msme"], "udyam_required": True, "min_revenue_inr": 1000000},
        "documents": ["Udyam Registration", "GST Returns", "Bank Statement", "Business Plan"],
        "timeline": "90 days",
        "official_link": "https://champions.gov.in/"
    },
    {
        "code": "MUDRA",
        "name_en": "PMMY - Pradhan Mantri MUDRA Yojana",
        "name_hi": "प्रधानमंत्री मुद्रा योजना",
        "category": "Central - Loan",
        "authority": "MUDRA / RBI",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Shishu ₹50k / Kishore ₹5L / Tarun ₹10L collateral-free loan",
        "grant_amount_label_hi": "शिशु ₹50 हजार / किशोर ₹5 लाख / तरुण ₹10 लाख ऋण",
        "summary_en": "Collateral-free loans for micro enterprises across three categories.",
        "summary_hi": "सूक्ष्म उद्यमों के लिए तीन श्रेणियों में बिना गारंटी ऋण।",
        "eligibility": {"stages": ["idea", "revenue"], "sectors": ["msme", "manufacturing", "services", "trading"]},
        "documents": ["KYC", "Business Proof", "Bank Statement", "Quotation for Machinery"],
        "timeline": "15-30 days",
        "official_link": "https://www.mudra.org.in/"
    },
    {
        "code": "CGTMSE",
        "name_en": "CGTMSE - Credit Guarantee for MSMEs",
        "name_hi": "सीजीटीएमएसई",
        "category": "Central - Credit Guarantee",
        "authority": "Ministry of MSME / SIDBI",
        "grant_amount_inr": 20000000,
        "grant_amount_label_en": "Collateral-free credit up to ₹2 crore",
        "grant_amount_label_hi": "बिना गारंटी ₹2 करोड़ तक ऋण",
        "summary_en": "Credit guarantee for MSME loans without collateral or third-party guarantee.",
        "summary_hi": "बिना संपार्श्विक के एमएसएमई ऋण के लिए क्रेडिट गारंटी।",
        "eligibility": {"stages": ["revenue"], "sectors": ["msme", "manufacturing", "services"], "udyam_required": True},
        "documents": ["Udyam Registration", "Bank Loan Application", "Project Report", "Financial Statements"],
        "timeline": "30-60 days",
        "official_link": "https://www.cgtmse.in/"
    },
    {
        "code": "80IAC",
        "name_en": "Section 80-IAC Tax Exemption",
        "name_hi": "धारा 80-IAC कर छूट",
        "category": "Central - Tax Benefit",
        "authority": "Income Tax Department / DPIIT",
        "grant_amount_inr": 0,
        "grant_amount_label_en": "100% tax exemption for 3 consecutive years (any 3 in first 10)",
        "grant_amount_label_hi": "3 वर्षों के लिए 100% कर छूट",
        "summary_en": "Full income-tax exemption on profits for eligible DPIIT-recognized startups.",
        "summary_hi": "पात्र DPIIT स्टार्टअप के लिए मुनाफे पर पूर्ण आयकर छूट।",
        "eligibility": {"stages": ["dpiit", "revenue"], "dpiit_required": True, "max_age_years": 10, "max_revenue_inr": 1000000000},
        "documents": ["DPIIT Certificate", "Form-1 Application", "Financial Statements", "CA Certificate"],
        "timeline": "90-120 days",
        "official_link": "https://www.startupindia.gov.in/content/sih/en/startupgov/startup-recognition-page.html"
    },
    {
        "code": "STARTUP_INDIA_HUB",
        "name_en": "Startup India Recognition (DPIIT)",
        "name_hi": "स्टार्टअप इंडिया मान्यता",
        "category": "Central - Recognition",
        "authority": "DPIIT",
        "grant_amount_inr": 0,
        "grant_amount_label_en": "Free recognition - unlocks 15+ benefits",
        "grant_amount_label_hi": "मुफ्त मान्यता - 15+ लाभ प्राप्त करें",
        "summary_en": "Recognition as a Startup by DPIIT gives access to tax benefits, easier compliance, IPR fast-track, and government schemes.",
        "summary_hi": "DPIIT से मान्यता प्राप्त करने पर कर लाभ, आसान अनुपालन, IPR फास्ट-ट्रैक मिलता है।",
        "eligibility": {"stages": ["idea", "dpiit", "revenue"], "max_age_years": 10, "max_revenue_inr": 1000000000},
        "documents": ["Incorporation Certificate", "PAN", "Brief Write-up on Innovation", "Founder Details"],
        "timeline": "5-7 days",
        "official_link": "https://www.startupindia.gov.in/"
    },
    {
        "code": "WEP",
        "name_en": "Women Entrepreneurship Platform (WEP)",
        "name_hi": "महिला उद्यमिता मंच",
        "category": "Central - Women",
        "authority": "NITI Aayog",
        "grant_amount_inr": 500000,
        "grant_amount_label_en": "Mentorship + funding linkages up to ₹5 lakh",
        "grant_amount_label_hi": "मेंटरशिप + ₹5 लाख तक",
        "summary_en": "Unified access portal for women entrepreneurs offering mentorship, funding, and market linkages.",
        "summary_hi": "महिला उद्यमियों के लिए एकीकृत पोर्टल।",
        "eligibility": {"stages": ["idea", "dpiit", "revenue"], "women_led_required": True},
        "documents": ["Aadhaar", "Business Registration", "Bank Details"],
        "timeline": "30 days",
        "official_link": "https://wep.gov.in/"
    },
    {
        "code": "STAND_UP_INDIA",
        "name_en": "Stand Up India Scheme",
        "name_hi": "स्टैंड अप इंडिया योजना",
        "category": "Central - Women/SC-ST",
        "authority": "SIDBI / Banks",
        "grant_amount_inr": 10000000,
        "grant_amount_label_en": "₹10 lakh to ₹1 crore composite loan",
        "grant_amount_label_hi": "₹10 लाख से ₹1 करोड़ तक ऋण",
        "summary_en": "Bank loans between ₹10 lakh and ₹1 crore for SC/ST and Women entrepreneurs setting up greenfield enterprises.",
        "summary_hi": "SC/ST और महिला उद्यमियों के लिए ग्रीनफील्ड उद्यम हेतु ऋण।",
        "eligibility": {"stages": ["idea", "revenue"], "women_led_bonus": True, "sectors": ["manufacturing", "services", "trading"]},
        "documents": ["KYC", "Business Plan", "Caste Certificate (if SC/ST)", "Bank Statement"],
        "timeline": "45 days",
        "official_link": "https://www.standupmitra.in/"
    },
    {
        "code": "NEW_GEN_IEDC",
        "name_en": "New Gen IEDC",
        "name_hi": "न्यू जेन आईईडीसी",
        "category": "Central - Student",
        "authority": "DST",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "Up to ₹25 lakh for student-led startups",
        "grant_amount_label_hi": "छात्र-नेतृत्व स्टार्टअप के लिए ₹25 लाख तक",
        "summary_en": "Supports engineering/science colleges to establish innovation cells and fund student startups.",
        "summary_hi": "इंजीनियरिंग/विज्ञान कॉलेजों में इनोवेशन सेल स्थापित करने हेतु।",
        "eligibility": {"stages": ["idea"], "sectors": ["tech", "hardware", "biotech"], "tech_bonus": True},
        "documents": ["Institute Affiliation", "Innovation Proposal", "Team Details"],
        "timeline": "120 days",
        "official_link": "https://dst.gov.in/scientific-programmes/scientific-engineering-research/technology-development-transfer/newgen-iedc"
    },
    {
        "code": "BIRAC_BIG",
        "name_en": "BIRAC BIG (Biotechnology Ignition Grant)",
        "name_hi": "बीआईआरएसी बीआईजी",
        "category": "Central - Biotech",
        "authority": "BIRAC / DBT",
        "grant_amount_inr": 5000000,
        "grant_amount_label_en": "Up to ₹50 lakh for biotech innovations",
        "grant_amount_label_hi": "बायोटेक इनोवेशन के लिए ₹50 लाख तक",
        "summary_en": "Early-stage funding for biotech entrepreneurs to validate proof of concept.",
        "summary_hi": "बायोटेक उद्यमियों के लिए प्रारंभिक फंडिंग।",
        "eligibility": {"stages": ["idea", "dpiit"], "sectors": ["biotech", "healthtech", "pharma"], "tech_bonus": True, "max_age_years": 5},
        "documents": ["Research Proposal", "PhD/Research Background (Preferred)", "Prototype Data"],
        "timeline": "6 months",
        "official_link": "https://birac.nic.in/big.php"
    },
    {
        "code": "AIM_ATAL",
        "name_en": "Atal Innovation Mission - AIM",
        "name_hi": "अटल इनोवेशन मिशन",
        "category": "Central - Innovation",
        "authority": "NITI Aayog",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Grants + incubation for innovators",
        "grant_amount_label_hi": "इनोवेटर्स के लिए अनुदान + इनक्यूबेशन",
        "summary_en": "Promotes culture of innovation and entrepreneurship through Atal Tinkering Labs and Incubation Centres.",
        "summary_hi": "इनोवेशन और उद्यमिता की संस्कृति को बढ़ावा।",
        "eligibility": {"stages": ["idea", "dpiit"], "sectors": ["any"], "tech_bonus": True},
        "documents": ["Innovation Proposal", "Founder Bio", "Prototype Details"],
        "timeline": "3-6 months",
        "official_link": "https://aim.gov.in/"
    },
    {
        "code": "PMEGP",
        "name_en": "Prime Minister's Employment Generation Programme (PMEGP)",
        "name_hi": "पीएमईजीपी",
        "category": "Central - Employment",
        "authority": "KVIC / Ministry of MSME",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "Up to ₹25 lakh loan with 15-35% subsidy",
        "grant_amount_label_hi": "₹25 लाख तक ऋण + 15-35% सब्सिडी",
        "summary_en": "Credit-linked subsidy for setting up new micro-enterprises in non-farm sector.",
        "summary_hi": "गैर-कृषि क्षेत्र में सूक्ष्म उद्यम स्थापित करने हेतु।",
        "eligibility": {"stages": ["idea"], "sectors": ["msme", "manufacturing", "services"]},
        "documents": ["Aadhaar", "Educational Certificate", "Project Report", "Caste Certificate (if applicable)"],
        "timeline": "45-60 days",
        "official_link": "https://www.kviconline.gov.in/pmegpeportal/"
    },
    {
        "code": "TREAD",
        "name_en": "TREAD - Trade Related Entrepreneurship Assistance for Women",
        "name_hi": "ट्रेड योजना",
        "category": "Central - Women",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 3000000,
        "grant_amount_label_en": "30% grant on total project cost (up to ₹30 lakh)",
        "grant_amount_label_hi": "परियोजना लागत पर 30% अनुदान (₹30 लाख तक)",
        "summary_en": "Empowers women through grants and loans for non-farm entrepreneurial activities.",
        "summary_hi": "गैर-कृषि उद्यमशीलता के लिए महिलाओं को अनुदान और ऋण।",
        "eligibility": {"stages": ["idea", "revenue"], "women_led_required": True, "sectors": ["manufacturing", "services", "handicraft"]},
        "documents": ["Aadhaar", "Business Plan", "Group/NGO Endorsement"],
        "timeline": "90 days",
        "official_link": "https://msme.gov.in/schemes/tread"
    },
    {
        "code": "ZED",
        "name_en": "MSME Sustainable (ZED) Certification",
        "name_hi": "एमएसएमई ज़ेड सर्टिफिकेशन",
        "category": "Central - MSME Quality",
        "authority": "Ministry of MSME / QCI",
        "grant_amount_inr": 200000,
        "grant_amount_label_en": "80% subsidy on certification cost",
        "grant_amount_label_hi": "प्रमाणन लागत पर 80% सब्सिडी",
        "summary_en": "Enables MSMEs to adopt Zero Defect Zero Effect practices with financial support.",
        "summary_hi": "एमएसएमई को ZED प्रथाओं को अपनाने में सहायता।",
        "eligibility": {"stages": ["revenue"], "sectors": ["manufacturing", "msme"], "udyam_required": True},
        "documents": ["Udyam Registration", "GST", "Quality Documentation"],
        "timeline": "60 days",
        "official_link": "https://zed.msme.gov.in/"
    },
    {
        "code": "CLCSS",
        "name_en": "Credit Linked Capital Subsidy Scheme (CLCSS)",
        "name_hi": "सीएलसीएसएस",
        "category": "Central - MSME",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "15% capital subsidy up to ₹15 lakh on machinery",
        "grant_amount_label_hi": "मशीनरी पर 15% पूंजी सब्सिडी (₹15 लाख तक)",
        "summary_en": "Subsidy for MSMEs upgrading plant and machinery in specified sub-sectors.",
        "summary_hi": "एमएसएमई को प्लांट और मशीनरी अपग्रेड करने हेतु सब्सिडी।",
        "eligibility": {"stages": ["revenue"], "sectors": ["manufacturing", "msme"], "udyam_required": True, "min_revenue_inr": 500000},
        "documents": ["Udyam Registration", "Bank Loan Sanction", "Invoice of Machinery"],
        "timeline": "90 days",
        "official_link": "https://www.dcmsme.gov.in/schemes/CLCSS_scheme.pdf"
    },
    {
        "code": "GENESIS",
        "name_en": "GENESIS - Gen-Next Support for Innovative Startups",
        "name_hi": "जेनेसिस",
        "category": "Central - Tier 2/3",
        "authority": "MeitY",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "Grant + incubation support in Tier 2/3 cities",
        "grant_amount_label_hi": "टियर 2/3 शहरों में अनुदान + इनक्यूबेशन",
        "summary_en": "Boost startup ecosystem in Tier-2 and Tier-3 cities with grants and mentorship.",
        "summary_hi": "टियर-2, टियर-3 शहरों में स्टार्टअप को बढ़ावा।",
        "eligibility": {"stages": ["idea", "dpiit"], "sectors": ["tech", "saas"], "tech_bonus": True},
        "documents": ["Company Registration", "Founder KYC", "Pitch Deck"],
        "timeline": "60 days",
        "official_link": "https://genesis.meity.gov.in/"
    },
    {
        "code": "DEVELOP_INDIA",
        "name_en": "Design Clinic Scheme",
        "name_hi": "डिज़ाइन क्लिनिक योजना",
        "category": "Central - Design",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 900000,
        "grant_amount_label_en": "75% subsidy up to ₹9 lakh for design projects",
        "grant_amount_label_hi": "डिजाइन परियोजनाओं के लिए ₹9 लाख तक 75% सब्सिडी",
        "summary_en": "Support MSMEs in incorporating professional design in their manufacturing.",
        "summary_hi": "एमएसएमई को डिज़ाइन अपनाने में सहायता।",
        "eligibility": {"stages": ["revenue"], "sectors": ["manufacturing", "msme"], "udyam_required": True},
        "documents": ["Udyam Registration", "Design Project Proposal"],
        "timeline": "90 days",
        "official_link": "https://www.designclinicsmsme.org/"
    },
    {
        "code": "MSE_CDP",
        "name_en": "MSE-CDP Cluster Development Programme",
        "name_hi": "एमएसई क्लस्टर विकास कार्यक्रम",
        "category": "Central - Cluster",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 10000000,
        "grant_amount_label_en": "Up to ₹1 crore for common facility centers",
        "grant_amount_label_hi": "सामान्य सुविधा केंद्रों के लिए ₹1 करोड़ तक",
        "summary_en": "Enhances productivity and competitiveness of MSME clusters.",
        "summary_hi": "एमएसएमई क्लस्टरों की उत्पादकता और प्रतिस्पर्धात्मकता बढ़ाना।",
        "eligibility": {"stages": ["revenue"], "sectors": ["manufacturing", "msme"], "udyam_required": True, "min_revenue_inr": 2000000},
        "documents": ["Cluster Association Registration", "Feasibility Report", "Land Documents"],
        "timeline": "6-12 months",
        "official_link": "https://msme.gov.in/mse-cdp"
    },
    {
        "code": "AGRISTACK",
        "name_en": "Agri-Tech Startup Grant (RKVY-RAFTAAR)",
        "name_hi": "एग्री-टेक स्टार्टअप अनुदान",
        "category": "Central - AgriTech",
        "authority": "Ministry of Agriculture",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "₹5 lakh (idea) to ₹25 lakh (seed) for agri startups",
        "grant_amount_label_hi": "कृषि स्टार्टअप के लिए ₹5 लाख से ₹25 लाख",
        "summary_en": "Nurtures agri-preneurs through incubation, seed funding, and mentorship.",
        "summary_hi": "कृषि उद्यमियों को इनक्यूबेशन और सीड फंडिंग।",
        "eligibility": {"stages": ["idea", "dpiit"], "sectors": ["agritech", "agriculture", "foodtech"], "tech_bonus": True},
        "documents": ["Business Plan", "Prototype", "Founder KYC"],
        "timeline": "120 days",
        "official_link": "https://rkvy.nic.in/"
    },
    {
        "code": "NABARD_INCUBATION",
        "name_en": "NABARD Rural Innovation Fund",
        "name_hi": "नाबार्ड ग्रामीण नवाचार निधि",
        "category": "Central - Rural",
        "authority": "NABARD",
        "grant_amount_inr": 5000000,
        "grant_amount_label_en": "Up to ₹50 lakh for rural innovations",
        "grant_amount_label_hi": "ग्रामीण नवाचार के लिए ₹50 लाख तक",
        "summary_en": "Supports rural startups focused on farming, dairy, rural livelihood.",
        "summary_hi": "कृषि, डेयरी, ग्रामीण आजीविका पर केंद्रित स्टार्टअप के लिए।",
        "eligibility": {"stages": ["idea", "revenue"], "sectors": ["agriculture", "rural", "dairy"], "rural_bonus": True},
        "documents": ["Project Proposal", "Impact Assessment", "Local Authority Endorsement"],
        "timeline": "6 months",
        "official_link": "https://www.nabard.org/"
    },
    {
        "code": "DEFENCE_iDEX",
        "name_en": "iDEX - Innovations for Defence Excellence",
        "name_hi": "आईडेक्स",
        "category": "Central - Defence",
        "authority": "Ministry of Defence",
        "grant_amount_inr": 15000000,
        "grant_amount_label_en": "Up to ₹1.5 crore for defence innovations",
        "grant_amount_label_hi": "रक्षा नवाचार के लिए ₹1.5 करोड़ तक",
        "summary_en": "Grants to startups solving challenges in defence and aerospace.",
        "summary_hi": "रक्षा और एयरोस्पेस के लिए स्टार्टअप।",
        "eligibility": {"stages": ["dpiit", "revenue"], "dpiit_required": True, "sectors": ["defence", "aerospace", "tech"], "tech_bonus": True},
        "documents": ["DPIIT Certificate", "Prototype", "Team Technical Background"],
        "timeline": "6-9 months",
        "official_link": "https://idex.gov.in/"
    },
    {
        "code": "PRARAMBH",
        "name_en": "Prarambh Startup Grant",
        "name_hi": "प्रारम्भ",
        "category": "Central - Early Stage",
        "authority": "Startup India",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh for BIMSTEC/SAARC market entry",
        "grant_amount_label_hi": "बिम्सटेक/सार्क बाजार प्रवेश के लिए ₹15 लाख तक",
        "summary_en": "Supports startups expanding to South Asian markets.",
        "summary_hi": "दक्षिण एशियाई बाजारों में विस्तार करने वाले स्टार्टअप।",
        "eligibility": {"stages": ["dpiit", "revenue"], "dpiit_required": True, "sectors": ["any"], "min_revenue_inr": 100000},
        "documents": ["DPIIT Certificate", "Business Model", "Market Entry Plan"],
        "timeline": "90 days",
        "official_link": "https://www.startupindia.gov.in/content/sih/en/international/prarambh.html"
    },
    {
        "code": "MP_STARTUP",
        "name_en": "Madhya Pradesh Startup Policy",
        "name_hi": "मध्य प्रदेश स्टार्टअप नीति",
        "category": "State - MP",
        "authority": "MP Government",
        "grant_amount_inr": 1800000,
        "grant_amount_label_en": "₹5 lakh grant + up to ₹18 lakh event support",
        "grant_amount_label_hi": "₹5 लाख अनुदान + ₹18 लाख तक इवेंट सहायता",
        "summary_en": "Investment subsidy and grants for startups registered in Madhya Pradesh.",
        "summary_hi": "मध्य प्रदेश में पंजीकृत स्टार्टअप के लिए निवेश सब्सिडी।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Madhya Pradesh"], "dpiit_required": False},
        "documents": ["MP Business Registration", "Founder Aadhaar", "Project Plan"],
        "timeline": "60 days",
        "official_link": "https://startup.mp.gov.in/"
    },
    {
        "code": "KA_ELEVATE",
        "name_en": "Karnataka Elevate 100",
        "name_hi": "कर्नाटक एलिवेट 100",
        "category": "State - Karnataka",
        "authority": "Karnataka IT-BT Dept",
        "grant_amount_inr": 5000000,
        "grant_amount_label_en": "Up to ₹50 lakh grant for shortlisted startups",
        "grant_amount_label_hi": "चयनित स्टार्टअप के लिए ₹50 लाख अनुदान",
        "summary_en": "Karnataka's flagship program identifying top 100 promising startups yearly.",
        "summary_hi": "कर्नाटक की प्रमुख योजना - शीर्ष 100 स्टार्टअप।",
        "eligibility": {"stages": ["dpiit", "revenue"], "states": ["Karnataka"], "tech_bonus": True},
        "documents": ["Karnataka Address Proof", "DPIIT Certificate", "Pitch Deck"],
        "timeline": "90-120 days",
        "official_link": "https://www.startupkarnataka.gov.in/"
    },
    {
        "code": "TN_STARTUP",
        "name_en": "Tamil Nadu Startup Seed Grant",
        "name_hi": "तमिलनाडु स्टार्टअप सीड ग्रांट",
        "category": "State - Tamil Nadu",
        "authority": "StartupTN",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh seed grant",
        "grant_amount_label_hi": "₹10 लाख तक सीड ग्रांट",
        "summary_en": "Seed funding for Tamil Nadu-registered startups.",
        "summary_hi": "तमिलनाडु में पंजीकृत स्टार्टअप के लिए सीड फंडिंग।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Tamil Nadu"]},
        "documents": ["TN Business Registration", "DPIIT (optional)", "Founder KYC"],
        "timeline": "60 days",
        "official_link": "https://startuptn.in/"
    },
    {
        "code": "MH_STARTUP",
        "name_en": "Maharashtra State Innovation Society Grant",
        "name_hi": "महाराष्ट्र स्टार्टअप ग्रांट",
        "category": "State - Maharashtra",
        "authority": "MSInS",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh + accelerator support",
        "grant_amount_label_hi": "₹15 लाख तक + एक्सेलेरेटर सहायता",
        "summary_en": "Grand challenges, grants, and incubation for Maharashtra startups.",
        "summary_hi": "महाराष्ट्र स्टार्टअप के लिए अनुदान।",
        "eligibility": {"stages": ["idea", "dpiit", "revenue"], "states": ["Maharashtra"]},
        "documents": ["Maharashtra Address Proof", "Innovation Details"],
        "timeline": "90 days",
        "official_link": "https://msins.in/"
    },
    {
        "code": "GJ_STARTUP",
        "name_en": "Gujarat Student Startup and Innovation Policy",
        "name_hi": "गुजरात स्टार्टअप नीति",
        "category": "State - Gujarat",
        "authority": "Gujarat Government",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "Up to ₹25 lakh seed support + ₹2 lakh POC",
        "grant_amount_label_hi": "₹25 लाख तक सीड + ₹2 लाख पीओसी",
        "summary_en": "SSIP supports student-led startups and innovators in Gujarat.",
        "summary_hi": "गुजरात में छात्र-नेतृत्व स्टार्टअप का समर्थन।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Gujarat"], "tech_bonus": True},
        "documents": ["Gujarat Address Proof", "College/Business Details"],
        "timeline": "90 days",
        "official_link": "https://ssipgujarat.in/"
    },
    {
        "code": "UP_STARTUP",
        "name_en": "UP Startup Policy - Seed Funding",
        "name_hi": "यूपी स्टार्टअप नीति",
        "category": "State - UP",
        "authority": "UP Government",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "₹15 lakh seed + ₹7.5 lakh sustenance allowance",
        "grant_amount_label_hi": "₹15 लाख सीड + ₹7.5 लाख भरण-पोषण भत्ता",
        "summary_en": "Financial assistance and mentorship for startups in Uttar Pradesh.",
        "summary_hi": "उत्तर प्रदेश में स्टार्टअप के लिए वित्तीय सहायता।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Uttar Pradesh"]},
        "documents": ["UP Business Registration", "Innovation Details"],
        "timeline": "90 days",
        "official_link": "https://startinup.up.gov.in/"
    },
    {
        "code": "TS_T_HUB",
        "name_en": "Telangana T-Hub Innovation Grant",
        "name_hi": "टी-हब इनोवेशन ग्रांट",
        "category": "State - Telangana",
        "authority": "T-Hub / Telangana Govt",
        "grant_amount_inr": 3000000,
        "grant_amount_label_en": "Up to ₹30 lakh + world-class incubation",
        "grant_amount_label_hi": "₹30 लाख तक + विश्वस्तरीय इनक्यूबेशन",
        "summary_en": "India's largest innovation ecosystem enabler, based in Hyderabad.",
        "summary_hi": "हैदराबाद स्थित भारत का सबसे बड़ा इनोवेशन इकोसिस्टम।",
        "eligibility": {"stages": ["dpiit", "revenue"], "states": ["Telangana"], "tech_bonus": True},
        "documents": ["Telangana Presence Proof", "DPIIT Certificate", "Pitch"],
        "timeline": "60-90 days",
        "official_link": "https://t-hub.co/"
    },
    {
        "code": "DL_STARTUP",
        "name_en": "Delhi Startup Policy",
        "name_hi": "दिल्ली स्टार्टअप नीति",
        "category": "State - Delhi",
        "authority": "Delhi Government",
        "grant_amount_inr": 2000000,
        "grant_amount_label_en": "Up to ₹20 lakh subsidy + interest reimbursement",
        "grant_amount_label_hi": "₹20 लाख तक सब्सिडी + ब्याज प्रतिपूर्ति",
        "summary_en": "Incentives for startups based in Delhi including rental & interest subsidies.",
        "summary_hi": "दिल्ली में स्थित स्टार्टअप के लिए किराया और ब्याज सब्सिडी।",
        "eligibility": {"stages": ["dpiit", "revenue"], "states": ["Delhi"]},
        "documents": ["Delhi Address Proof", "DPIIT Certificate"],
        "timeline": "90 days",
        "official_link": "https://it.delhi.gov.in/"
    },
    {
        "code": "RJ_ISTART",
        "name_en": "Rajasthan iStart",
        "name_hi": "राजस्थान आईस्टार्ट",
        "category": "State - Rajasthan",
        "authority": "Rajasthan Government",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh grant + QRate certification",
        "grant_amount_label_hi": "₹10 लाख तक अनुदान + QRate प्रमाणन",
        "summary_en": "Rajasthan's flagship platform to nurture startups.",
        "summary_hi": "राजस्थान का प्रमुख स्टार्टअप मंच।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Rajasthan"]},
        "documents": ["Rajasthan Address", "Business Plan"],
        "timeline": "60 days",
        "official_link": "https://istart.rajasthan.gov.in/"
    },
    {
        "code": "KL_STARTUP",
        "name_en": "Kerala Startup Mission - Seed Fund",
        "name_hi": "केरल स्टार्टअप मिशन",
        "category": "State - Kerala",
        "authority": "KSUM",
        "grant_amount_inr": 1200000,
        "grant_amount_label_en": "Up to ₹12 lakh idea/prototype funding",
        "grant_amount_label_hi": "₹12 लाख तक विचार/प्रोटोटाइप फंडिंग",
        "summary_en": "Nodal agency for entrepreneurship development in Kerala.",
        "summary_hi": "केरल में उद्यमिता विकास हेतु नोडल एजेंसी।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Kerala"], "tech_bonus": True},
        "documents": ["Kerala Presence", "Innovation Details", "Prototype"],
        "timeline": "60 days",
        "official_link": "https://startupmission.kerala.gov.in/"
    },
    {
        "code": "WB_STARTUP",
        "name_en": "West Bengal Startup Policy",
        "name_hi": "पश्चिम बंगाल स्टार्टअप नीति",
        "category": "State - WB",
        "authority": "WB Government",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh startup grant",
        "grant_amount_label_hi": "₹15 लाख तक स्टार्टअप अनुदान",
        "summary_en": "Seed grants and incentives for startups in West Bengal.",
        "summary_hi": "पश्चिम बंगाल में स्टार्टअप के लिए अनुदान।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["West Bengal"]},
        "documents": ["WB Address Proof", "Business Plan"],
        "timeline": "90 days",
        "official_link": "https://wbstartup.in/"
    },
    {
        "code": "PB_STARTUP",
        "name_en": "Punjab Innovation Mission",
        "name_hi": "पंजाब इनोवेशन मिशन",
        "category": "State - Punjab",
        "authority": "Punjab Government",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh grant",
        "grant_amount_label_hi": "₹10 लाख तक अनुदान",
        "summary_en": "Supports Punjab-based startups with grants and mentorship.",
        "summary_hi": "पंजाब स्थित स्टार्टअप के लिए अनुदान।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Punjab"]},
        "documents": ["Punjab Address", "Business Details"],
        "timeline": "90 days",
        "official_link": "https://startuppunjab.punjab.gov.in/"
    },
    {
        "code": "HR_STARTUP",
        "name_en": "Haryana Startup Policy",
        "name_hi": "हरियाणा स्टार्टअप नीति",
        "category": "State - Haryana",
        "authority": "Haryana Government",
        "grant_amount_inr": 3000000,
        "grant_amount_label_en": "Up to ₹30 lakh support + reimbursements",
        "grant_amount_label_hi": "₹30 लाख तक सहायता",
        "summary_en": "Attractive incentives for startups located in Haryana.",
        "summary_hi": "हरियाणा स्थित स्टार्टअप के लिए प्रोत्साहन।",
        "eligibility": {"stages": ["dpiit", "revenue"], "states": ["Haryana"]},
        "documents": ["Haryana Address Proof", "DPIIT Certificate"],
        "timeline": "60-90 days",
        "official_link": "https://itharyana.gov.in/"
    },
    {
        "code": "OD_STARTUP",
        "name_en": "Odisha Startup Policy",
        "name_hi": "ओडिशा स्टार्टअप नीति",
        "category": "State - Odisha",
        "authority": "Odisha Government",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh grant + rent subsidy",
        "grant_amount_label_hi": "₹15 लाख अनुदान + किराया सब्सिडी",
        "summary_en": "Emerging startup hub with attractive incentives.",
        "summary_hi": "उभरता स्टार्टअप हब - आकर्षक प्रोत्साहन।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Odisha"]},
        "documents": ["Odisha Presence Proof", "Innovation Details"],
        "timeline": "90 days",
        "official_link": "https://startupodisha.gov.in/"
    },
    {
        "code": "BR_STARTUP",
        "name_en": "Bihar Startup Policy",
        "name_hi": "बिहार स्टार्टअप नीति",
        "category": "State - Bihar",
        "authority": "Bihar Government",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh interest-free loan",
        "grant_amount_label_hi": "₹10 लाख तक ब्याज मुक्त ऋण",
        "summary_en": "Interest-free loans and incentives for Bihar-based startups.",
        "summary_hi": "बिहार स्थित स्टार्टअप हेतु ब्याज मुक्त ऋण।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Bihar"]},
        "documents": ["Bihar Address Proof", "Business Plan"],
        "timeline": "60 days",
        "official_link": "https://startup.bihar.gov.in/"
    },
    {
        "code": "AP_STARTUP",
        "name_en": "Andhra Pradesh Innovation Society",
        "name_hi": "आंध्र प्रदेश इनोवेशन",
        "category": "State - AP",
        "authority": "APIS",
        "grant_amount_inr": 2500000,
        "grant_amount_label_en": "Up to ₹25 lakh grant + reimbursements",
        "grant_amount_label_hi": "₹25 लाख अनुदान + प्रतिपूर्ति",
        "summary_en": "Fosters innovation and startups in Andhra Pradesh.",
        "summary_hi": "आंध्र प्रदेश में नवाचार और स्टार्टअप।",
        "eligibility": {"stages": ["dpiit", "revenue"], "states": ["Andhra Pradesh"]},
        "documents": ["AP Address Proof", "DPIIT (optional)"],
        "timeline": "90 days",
        "official_link": "https://apinnovationsociety.com/"
    },
    {
        "code": "JK_STARTUP",
        "name_en": "J&K Startup Policy",
        "name_hi": "जम्मू-कश्मीर स्टार्टअप",
        "category": "State - J&K",
        "authority": "J&K Government",
        "grant_amount_inr": 3000000,
        "grant_amount_label_en": "Up to ₹30 lakh grant + rent subsidy",
        "grant_amount_label_hi": "₹30 लाख अनुदान",
        "summary_en": "Attractive incentives for startups in Jammu & Kashmir.",
        "summary_hi": "जम्मू और कश्मीर में स्टार्टअप के लिए प्रोत्साहन।",
        "eligibility": {"stages": ["idea", "dpiit"], "states": ["Jammu and Kashmir"]},
        "documents": ["J&K Address", "Innovation Proposal"],
        "timeline": "90 days",
        "official_link": "https://startup.jk.gov.in/"
    },
    {
        "code": "EXPORT_MDA",
        "name_en": "Market Development Assistance (MDA) for MSMEs",
        "name_hi": "एमएसएमई हेतु बाजार विकास सहायता",
        "category": "Central - Export",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 500000,
        "grant_amount_label_en": "Up to ₹5 lakh subsidy for participation in international trade fairs",
        "grant_amount_label_hi": "अंतरराष्ट्रीय व्यापार मेलों में भाग लेने हेतु ₹5 लाख तक",
        "summary_en": "Reimburses travel and stall costs for MSMEs participating in international exhibitions.",
        "summary_hi": "एमएसएमई के लिए अंतरराष्ट्रीय प्रदर्शनियों में भागीदारी।",
        "eligibility": {"stages": ["revenue"], "sectors": ["export", "msme", "manufacturing"], "udyam_required": True},
        "documents": ["Udyam Registration", "Export IEC Code", "Fair Invitation"],
        "timeline": "45 days",
        "official_link": "https://msme.gov.in/international-cooperation-scheme"
    },
    {
        "code": "IPR_SUPPORT",
        "name_en": "SIPP - Startups IPR Protection",
        "name_hi": "स्टार्टअप आईपीआर सुरक्षा",
        "category": "Central - IPR",
        "authority": "DPIIT / CGPDTM",
        "grant_amount_inr": 100000,
        "grant_amount_label_en": "80% rebate on patent filing + free legal facilitation",
        "grant_amount_label_hi": "पेटेंट फाइलिंग पर 80% छूट + मुफ्त कानूनी सहायता",
        "summary_en": "Fast-track patent filing and rebate on fees for DPIIT-recognized startups.",
        "summary_hi": "DPIIT स्टार्टअप के लिए तेज पेटेंट फाइलिंग।",
        "eligibility": {"stages": ["dpiit", "revenue"], "dpiit_required": True, "tech_bonus": True},
        "documents": ["DPIIT Certificate", "Patent Draft/Application"],
        "timeline": "45-90 days",
        "official_link": "https://ipindia.gov.in/"
    },
    {
        "code": "GRAM_UDYOG",
        "name_en": "Gramodyog Vikas Yojana",
        "name_hi": "ग्रामोद्योग विकास योजना",
        "category": "Central - Rural",
        "authority": "KVIC",
        "grant_amount_inr": 800000,
        "grant_amount_label_en": "Up to ₹8 lakh grant + training",
        "grant_amount_label_hi": "₹8 लाख तक अनुदान + प्रशिक्षण",
        "summary_en": "Supports village industries: honey, khadi, pottery, agarbatti units.",
        "summary_hi": "ग्रामोद्योगों को सहायता।",
        "eligibility": {"stages": ["idea", "revenue"], "sectors": ["rural", "handicraft"], "rural_bonus": True},
        "documents": ["Aadhaar", "Village Business Details"],
        "timeline": "60 days",
        "official_link": "https://www.kvic.gov.in/"
    },
    {
        "code": "SFURTI",
        "name_en": "SFURTI - Traditional Industries",
        "name_hi": "स्फूर्ति योजना",
        "category": "Central - Traditional",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 8000000,
        "grant_amount_label_en": "Up to ₹8 crore per cluster for traditional industries",
        "grant_amount_label_hi": "पारंपरिक उद्योगों के लिए ₹8 करोड़ तक",
        "summary_en": "Cluster-based development of traditional industries like handicrafts.",
        "summary_hi": "पारंपरिक उद्योगों जैसे हस्तशिल्प का क्लस्टर विकास।",
        "eligibility": {"stages": ["revenue"], "sectors": ["handicraft", "traditional", "khadi"]},
        "documents": ["Cluster Association", "Artisan List", "Project Plan"],
        "timeline": "6-12 months",
        "official_link": "https://sfurti.msme.gov.in/"
    },
    {
        "code": "ASPIRE",
        "name_en": "ASPIRE - Rural Enterprise Program",
        "name_hi": "एस्पायर योजना",
        "category": "Central - Agro-Rural",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 1000000,
        "grant_amount_label_en": "Up to ₹10 lakh for agro-processing startups",
        "grant_amount_label_hi": "एग्रो-प्रोसेसिंग स्टार्टअप के लिए ₹10 लाख तक",
        "summary_en": "Promotes innovation in the agriculture and rural industry sector.",
        "summary_hi": "कृषि और ग्रामीण उद्योग में नवाचार।",
        "eligibility": {"stages": ["idea", "revenue"], "sectors": ["agritech", "foodtech", "rural"], "rural_bonus": True},
        "documents": ["Business Plan", "Rural Location Proof"],
        "timeline": "90 days",
        "official_link": "https://msme.gov.in/aspire"
    },
    {
        "code": "PM_VISHWAKARMA",
        "name_en": "PM Vishwakarma Yojana",
        "name_hi": "पीएम विश्वकर्मा योजना",
        "category": "Central - Artisan",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 300000,
        "grant_amount_label_en": "₹3 lakh loan (2 tranches) + toolkit + training",
        "grant_amount_label_hi": "₹3 लाख ऋण + टूलकिट + प्रशिक्षण",
        "summary_en": "Financial support for 18 traditional trades including carpenters, weavers, potters.",
        "summary_hi": "पारंपरिक कारीगरों के लिए वित्तीय सहायता।",
        "eligibility": {"stages": ["idea", "revenue"], "sectors": ["artisan", "handicraft", "traditional"]},
        "documents": ["Aadhaar", "Trade Proof", "Bank Account"],
        "timeline": "60 days",
        "official_link": "https://pmvishwakarma.gov.in/"
    },
    {
        "code": "FSSAI_STARTUP",
        "name_en": "FSSAI Food Startup Grant",
        "name_hi": "एफएसएसएआई फूड स्टार्टअप",
        "category": "Central - FoodTech",
        "authority": "FSSAI / MoFPI",
        "grant_amount_inr": 5000000,
        "grant_amount_label_en": "Up to ₹50 lakh for food processing startups (PMFME)",
        "grant_amount_label_hi": "फूड प्रोसेसिंग स्टार्टअप के लिए ₹50 लाख तक",
        "summary_en": "Credit-linked capital subsidy for food processing enterprises.",
        "summary_hi": "फूड प्रोसेसिंग उद्यमों के लिए क्रेडिट-लिंक्ड सब्सिडी।",
        "eligibility": {"stages": ["revenue"], "sectors": ["foodtech", "food-processing", "msme"], "udyam_required": True},
        "documents": ["Udyam Registration", "FSSAI License", "Project Report"],
        "timeline": "90 days",
        "official_link": "https://pmfme.mofpi.gov.in/"
    },
    {
        "code": "MSME_INNOVATION",
        "name_en": "MSME Innovative Scheme (Ideation, IPR, Design, Digital)",
        "name_hi": "एमएसएमई इनोवेटिव योजना",
        "category": "Central - MSME Innovation",
        "authority": "Ministry of MSME",
        "grant_amount_inr": 1500000,
        "grant_amount_label_en": "Up to ₹15 lakh for prototype + IPR + design + digital adoption",
        "grant_amount_label_hi": "प्रोटोटाइप + आईपीआर + डिज़ाइन + डिजिटल हेतु ₹15 लाख तक",
        "summary_en": "Combined support for MSMEs on ideation, IPR, design, and digital transformation.",
        "summary_hi": "एमएसएमई को नवाचार हेतु संयुक्त सहायता।",
        "eligibility": {"stages": ["revenue"], "sectors": ["msme", "manufacturing"], "udyam_required": True},
        "documents": ["Udyam Registration", "Innovation Proposal"],
        "timeline": "90 days",
        "official_link": "https://innovative.msme.gov.in/"
    },
    {
        "code": "SIDBI_STARTUP",
        "name_en": "SIDBI Startup Mitra",
        "name_hi": "सिडबी स्टार्टअप मित्र",
        "category": "Central - Debt",
        "authority": "SIDBI",
        "grant_amount_inr": 20000000,
        "grant_amount_label_en": "Debt/equity funding up to ₹2 crore",
        "grant_amount_label_hi": "₹2 करोड़ तक ऋण/इक्विटी",
        "summary_en": "One-stop shop for startups seeking debt/equity from SIDBI.",
        "summary_hi": "स्टार्टअप के लिए ऋण/इक्विटी।",
        "eligibility": {"stages": ["dpiit", "revenue"], "dpiit_required": True, "min_revenue_inr": 500000},
        "documents": ["DPIIT Certificate", "Audited Financials", "Business Plan"],
        "timeline": "60-90 days",
        "official_link": "https://sidbistartupmitra.in/"
    },
    {
        "code": "EMRS_MOBILITY",
        "name_en": "EMPS - Electric Mobility Promotion Scheme",
        "name_hi": "इलेक्ट्रिक मोबिलिटी प्रोत्साहन",
        "category": "Central - EV",
        "authority": "Ministry of Heavy Industries",
        "grant_amount_inr": 10000000,
        "grant_amount_label_en": "Subsidies for EV manufacturers up to ₹1 crore",
        "grant_amount_label_hi": "EV निर्माताओं हेतु ₹1 करोड़ तक सब्सिडी",
        "summary_en": "Boosts EV manufacturing and adoption in India.",
        "summary_hi": "भारत में EV निर्माण को बढ़ावा।",
        "eligibility": {"stages": ["revenue"], "sectors": ["ev", "manufacturing", "cleantech"], "tech_bonus": True},
        "documents": ["Manufacturing License", "ARAI/ICAT Certification"],
        "timeline": "90 days",
        "official_link": "https://heavyindustries.gov.in/emps-2024"
    }
]
